<?xml version="1.0"?>
<robot name="arm_2DOF" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="arm_base_length" value="0.1" />
    <xacro:property name="arm_base_width" value="0.1" />
    <xacro:property name="arm_base_height" value="0.02" />
    <xacro:property name="arm_link_radius" value="0.02" />
    <xacro:property name="arm_link_length" value="0.3" />

    <xacro:macro name="arm_link" params="prefix">
        <link name="${prefix}_link">
            <visual>
                <geometry>
                    <cylinder radius="${arm_link_radius}" length="${arm_link_length}"/>
                </geometry>
                <origin xyz="0 0 ${arm_link_length / 2}" rpy="0 0 0"/>
                <material name="yellow"/>
            </visual>

            <collision>
                <geometry>
                    <sphere radius="${arm_link_radius}"/>
                </geometry>
                <origin xyz="0 0 0" rpy="0 0 0"/>
            </collision>

            <xacro:cyl_inertia m="0.3" r="${arm_link_radius}" h="${arm_link_length}"
                               o_xyz="0 0 ${arm_link_length/2}" o_rpy="0 0 0" />
        </link>
    </xacro:macro>

    <link name="arm_base_link">
        <visual>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <material name="orange"/>
        </visual>

        <collision>
            <geometry>
                <box size="${arm_base_length} ${arm_base_width} ${arm_base_height}"/>
            </geometry>
            <origin xyz="0 0 ${arm_base_height / 2.0}" rpy="0 0 0"/>
        </collision>

        <xacro:box_inertia m="0.5" x="${arm_base_length}" y="${arm_base_width}" z="${arm_base_height}"
                           o_xyz="0 0 ${arm_base_height / 2.0}" o_rpy="0 0 0" />
    </link>

    <joint name="base_arm_base_joint" type="fixed">
        <parent link="base_link" />
        <child link="arm_base_link" />
        <origin xyz="${base_length/4} 0 ${base_height + arm_base_height / 2}" rpy="0 0 0"/>
    </joint>

    <xacro:arm_link prefix="forearm" />
    <xacro:arm_link prefix="hand" />

    <joint name="arm_base_forearm_joint" type="revolute">
        <parent link="arm_base_link" />
        <child link="forearm_link" />
        <origin xyz="0 0 ${arm_base_height / 2}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="${pi /2}" effort="100" velocity="100"/>
        <dynamics damping="0.3" friction="0.3"/>
    </joint>

    <joint name="forearm_hand_joint" type="revolute">
        <parent link="forearm_link" />
        <child link="hand_link" />
        <origin xyz="0 0 ${arm_link_length}" rpy="0 0 0"/>
        <axis xyz="0 1 0"/>
        <limit lower="0" upper="${pi /2}" effort="100" velocity="100"/>
        <dynamics damping="0.3" friction="0.3"/>
    </joint>

</robot>